---
apiVersion: v1
kind: Service
metadata:
  name: device-radius-nodeport
spec:
  selector:
    name: device-radius-pod
  ports:
    - name: radius-auth
      protocol: UDP
      port: 1812
      targetPort: 1812
    - name: radius-accounting
      protocol: UDP
      port: 1813
      targetPort: 1813
  type: NodePort
  externalTrafficPolicy: Local
