apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  proxy.conf: |
    proxy server {
    	default_fallback = no
    }
    
    home_server nps01 {
    	type = auth+acct
    	ipaddr = 192.0.2.1
    	port = 1812
    	proto = udp
    	secret = proxy123
    	response_window = 20
    	zombie_period = 40
    	revive_interval = 120
    	status_check = status-server
    	check_interval = 30
    	check_timeout = 4
    	num_answers_to_alive = 3
    	max_outstanding = 65536
    	coa {
    		irt = 2
    		mrt = 16
    		mrc = 5
    		mrd = 30
    	}
    	limit {
    	      max_connections = 16
    	      max_requests = 0
    	      lifetime = 0
    	      idle_timeout = 0
    	}
    }
    
    home_server nps02 {
    	type = auth+acct
    	ipaddr = 192.0.2.2
    	port = 1812
    	proto = udp
    	secret = proxy123
    	response_window = 20
    	zombie_period = 40
    	revive_interval = 120
    	status_check = status-server
    	check_interval = 30
    	check_timeout = 4
    	num_answers_to_alive = 3
    	max_outstanding = 65536
    	coa {
    		irt = 2
    		mrt = 16
    		mrc = 5
    		mrd = 30
    	}
    	limit {
    	      max_connections = 16
    	      max_requests = 0
    	      lifetime = 0
    	      idle_timeout = 0
    	}
    }
    
    home_server_pool nps_failover {
    	type = fail-over
    	home_server = nps01
    	home_server = nps02
    }
    
    realm nps {
    	pool = nps_failover
    }
    realm NULL {
            pool = nps_failover
    }
